# Generated by Django 2.2.10 on 2021-12-14 15:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrower', models.CharField(max_length=20)),
                ('borrower_card', models.CharField(blank=True, max_length=8)),
                ('borrower_email', models.EmailField(blank=True, max_length=50)),
                ('borrower_phone_number', models.CharField(blank=True, max_length=30)),
                ('book', models.CharField(max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('start_day', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_day', models.DateTimeField(default=datetime.datetime(2021, 12, 21, 15, 30, 0, 999922, tzinfo=utc))),
                ('periode', models.PositiveIntegerField(default=0)),
                ('open_or_close', models.IntegerField(choices=[(0, 'Open'), (1, 'Closed')], default=0)),
                ('delay_days', models.IntegerField(default=0)),
                ('final_status', models.CharField(default='Unknown', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.CharField(blank=True, max_length=20)),
                ('closed_by', models.CharField(default='', max_length=20)),
                ('closed_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField(default=20)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], default='m', max_length=10)),
                ('city', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('phone_number', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.CharField(default='', max_length=20)),
                ('updated_by', models.CharField(default='', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('card_number', models.CharField(default='', max_length=8)),
                ('expired_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operation_type', models.CharField(choices=[('success', 'Create'), ('warning', 'Update'), ('danger', 'Delete'), ('info', 'Close')], default='success', max_length=20)),
                ('target_model', models.CharField(default='', max_length=20)),
                ('detail', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='created',
        ),
        migrations.RemoveField(
            model_name='book',
            name='uploaded',
        ),
        migrations.RemoveField(
            model_name='category',
            name='created',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='created',
        ),
        migrations.AddField(
            model_name='book',
            name='bookshelf_number',
            field=models.CharField(default='0001', max_length=10, verbose_name='Bookshelf Number'),
        ),
        migrations.AddField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Time'),
        ),
        migrations.AddField(
            model_name='book',
            name='floor_number',
            field=models.IntegerField(choices=[(1, '1st'), (2, '2nd'), (3, '3rd')], default=1),
        ),
        migrations.AddField(
            model_name='book',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='book',
            name='updated_by',
            field=models.CharField(default='yaozeliang', max_length=20),
        ),
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='publisher',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='publisher',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='publisher',
            name='updated_by',
            field=models.CharField(default='yaozeliang', max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='book.Category'),
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publisher', to='book.Publisher'),
        ),
        migrations.AlterField(
            model_name='book',
            name='quantity',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.IntegerField(choices=[(0, 'On loan'), (1, 'In Stock')], default=1),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile/%Y%m%d/')),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
