# Generated by Django 3.2.6 on 2021-12-27 13:10

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20211220_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='file',
            field=models.FileField(default=None, null=True, upload_to='media/files/'),
        ),
        migrations.AddField(
            model_name='class',
            name='reference',
            field=models.CharField(default=None, max_length=100, verbose_name='reference_book'),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='end_day',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 3, 13, 10, 41, 632027, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reference_book',
            name='ISBN',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='reference_book',
            name='author',
            field=models.CharField(max_length=255, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='reference_book',
            name='bookname',
            field=models.CharField(max_length=255, verbose_name='BookName'),
        ),
        migrations.AlterField(
            model_name='reference_book',
            name='link',
            field=models.CharField(max_length=255, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='reference_book',
            name='publisher',
            field=models.CharField(max_length=255, verbose_name='Publisher'),
        ),
        migrations.AlterField(
            model_name='reference_book',
            name='type',
            field=models.CharField(max_length=255, verbose_name='Type'),
        ),
        migrations.CreateModel(
            name='Buybook',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('coursecode', models.CharField(blank=True, max_length=255, null=True)),
                ('coursename', models.CharField(blank=True, max_length=255, null=True)),
                ('isbn', models.CharField(blank=True, max_length=255, null=True)),
                ('bookname', models.CharField(blank=True, max_length=255, null=True)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, default='0', max_length=3)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher', to='book.teacher')),
            ],
        ),
    ]
